"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import sys
import logging
from npdfhir.middleware import HealthCheckMiddleware

# Detect if tests are being run
TESTING = 'test' in sys.argv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('NPD_DJANGO_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(config('DEBUG'))
TESTING = sys.argv[1:2] == ['test']


if DEBUG:
    ALLOWED_HOSTS = ['localhost','127.0.0.1','0.0.0.0']
else:
    ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS").split(',')

INTERNAL_APIS = config("DJANGO_ALLOWED_HOSTS").split(',')

# Application definition

INSTALLED_APPS = [
    'npdfhir.apps.NPDFHIRConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'drf_yasg',
    'xmlrunner',
]

if not TESTING:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'npdfhir.middleware.HealthCheckMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not TESTING:
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')
    # This must come at the end.

# We want the fhir urls to be entirely open
CORS_URLS_REGEX = r'^/fhir/.*$'
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_METHODS = ['GET']

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # NOTE: (@abachman-dsac) this setup allows frontend/ to build directly
            # into provider_directory/static/ and provider_directory.views.landing to
            # reference the resulting index.html
            os.path.join(BASE_DIR, 'provider_directory', 'static'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('NPD_DB_ENGINE'),
        'USER': config('NPD_DB_USER'),
        'PASSWORD': config('NPD_DB_PASSWORD'),
        'HOST': config('NPD_DB_HOST'),
        'NAME': config('NPD_DB_NAME'),
        'PORT': config('NPD_DB_PORT'),
        "TEST": {
            # Django will create a new test DB with this name prefix
            "NAME": f"{os.getenv('NPD_DB_NAME', 'npd')}",
            "MIRROR": "default",                 # optional: avoids creating a test DB
        },
        'OPTIONS': {
            'options': '-c search_path=npd,public'
        }
    }
}

TEST_RUNNER = 'xmlrunner.extra.djangotestrunner.XMLTestRunner'
# Directory where XML reports will be written
TEST_OUTPUT_DIR = './artifacts/test-reports'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'provider_directory', 'static'),
]

# STATICFILES_DIRS = [
#        os.path.join(BASE_DIR, "static"),
#    ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/django_cache",
    }
}

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False
}

LOG_LEVEL = os.environ.get("LOG_LEVEL", logging.INFO)
LOGGING = {
    "version": 1,
    # This will leave the default Django logging behavior in place
    "disable_existing_loggers": False,
    # Custom handler config that gets log messages and outputs them to console
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": LOG_LEVEL,
        },
    },
    "loggers": {
        # Send everything to console
        "": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
        },
    },
}
