--
-- Data for Name: fips_state; Type: TABLE DATA; Schema: ndh; Owner: -
--

INSERT INTO ndh.fips_state VALUES ('01', 'Alabama', 'AL');
INSERT INTO ndh.fips_state VALUES ('02', 'Alaska', 'AK');
INSERT INTO ndh.fips_state VALUES ('04', 'Arizona', 'AZ');
INSERT INTO ndh.fips_state VALUES ('05', 'Arkansas', 'AR');
INSERT INTO ndh.fips_state VALUES ('06', 'California', 'CA');
INSERT INTO ndh.fips_state VALUES ('08', 'Colorado', 'CO');
INSERT INTO ndh.fips_state VALUES ('09', 'Connecticut', 'CT');
INSERT INTO ndh.fips_state VALUES ('10', 'Delaware', 'DE');
INSERT INTO ndh.fips_state VALUES ('11', 'District of Columbia', 'DC');
INSERT INTO ndh.fips_state VALUES ('12', 'Florida', 'FL');
INSERT INTO ndh.fips_state VALUES ('13', 'Georgia', 'GA');
INSERT INTO ndh.fips_state VALUES ('15', 'Hawaii', 'HI');
INSERT INTO ndh.fips_state VALUES ('16', 'Idaho', 'ID');
INSERT INTO ndh.fips_state VALUES ('17', 'Illinois', 'IL');
INSERT INTO ndh.fips_state VALUES ('18', 'Indiana', 'IN');
INSERT INTO ndh.fips_state VALUES ('19', 'Iowa', 'IA');
INSERT INTO ndh.fips_state VALUES ('20', 'Kansas', 'KS');
INSERT INTO ndh.fips_state VALUES ('21', 'Kentucky', 'KY');
INSERT INTO ndh.fips_state VALUES ('22', 'Louisiana', 'LA');
INSERT INTO ndh.fips_state VALUES ('23', 'Maine', 'ME');
INSERT INTO ndh.fips_state VALUES ('24', 'Maryland', 'MD');
INSERT INTO ndh.fips_state VALUES ('25', 'Massachusetts', 'MA');
INSERT INTO ndh.fips_state VALUES ('26', 'Michigan', 'MI');
INSERT INTO ndh.fips_state VALUES ('27', 'Minnesota', 'MN');
INSERT INTO ndh.fips_state VALUES ('28', 'Mississippi', 'MS');
INSERT INTO ndh.fips_state VALUES ('29', 'Missouri', 'MO');
INSERT INTO ndh.fips_state VALUES ('30', 'Montana', 'MT');
INSERT INTO ndh.fips_state VALUES ('31', 'Nebraska', 'NE');
INSERT INTO ndh.fips_state VALUES ('32', 'Nevada', 'NV');
INSERT INTO ndh.fips_state VALUES ('33', 'New Hampshire', 'NH');
INSERT INTO ndh.fips_state VALUES ('34', 'New Jersey', 'NJ');
INSERT INTO ndh.fips_state VALUES ('35', 'New Mexico', 'NM');
INSERT INTO ndh.fips_state VALUES ('36', 'New York', 'NY');
INSERT INTO ndh.fips_state VALUES ('37', 'North Carolina', 'NC');
INSERT INTO ndh.fips_state VALUES ('38', 'North Dakota', 'ND');
INSERT INTO ndh.fips_state VALUES ('39', 'Ohio', 'OH');
INSERT INTO ndh.fips_state VALUES ('40', 'Oklahoma', 'OK');
INSERT INTO ndh.fips_state VALUES ('41', 'Oregon', 'OR');
INSERT INTO ndh.fips_state VALUES ('42', 'Pennsylvania', 'PA');
INSERT INTO ndh.fips_state VALUES ('44', 'Rhode Island', 'RI');
INSERT INTO ndh.fips_state VALUES ('45', 'South Carolina', 'SC');
INSERT INTO ndh.fips_state VALUES ('46', 'South Dakota', 'SD');
INSERT INTO ndh.fips_state VALUES ('47', 'Tennessee', 'TN');
INSERT INTO ndh.fips_state VALUES ('48', 'Texas', 'TX');
INSERT INTO ndh.fips_state VALUES ('49', 'Utah', 'UT');
INSERT INTO ndh.fips_state VALUES ('50', 'Vermont', 'VT');
INSERT INTO ndh.fips_state VALUES ('51', 'Virginia', 'VA');
INSERT INTO ndh.fips_state VALUES ('53', 'Washington', 'WA');
INSERT INTO ndh.fips_state VALUES ('54', 'West Virginia', 'WV');
INSERT INTO ndh.fips_state VALUES ('55', 'Wisconsin', 'WI');
INSERT INTO ndh.fips_state VALUES ('56', 'Wyoming', 'WY');
INSERT INTO ndh.fips_state VALUES ('60', 'American Samoa', 'AS');
INSERT INTO ndh.fips_state VALUES ('66', 'Guam', 'GU');
INSERT INTO ndh.fips_state VALUES ('69', 'Commonwealth of the Northern Mariana Islands', 'MP');
INSERT INTO ndh.fips_state VALUES ('72', 'Puerto Rico', 'PR');
INSERT INTO ndh.fips_state VALUES ('74', 'U.S. Minor Outlying Islands', 'UM');
INSERT INTO ndh.fips_state VALUES ('78', 'United States Virgin Islands', 'VI');
